### PR TITLE
Pull Request for Code Review

### PR DESCRIPTION
**Pull request by frederico-miranda**
This is a pull request opened for the purpose of receiving a code review.

### CODE REVIEW

**Comment by mikenath223** [comment]
Its done.

**Comment by mikenath223** [comment]
correct
As for this issue you talked about you will actually see that their is an advert if you view the main page on a wider screen.
Here 
Smashing Magazine — For Web Designers And Developers — Smashing Magazine - Google Chrome 29_10_2019 09_19_58 AM

**Comment by mikenath223** [comment]
Please view above comment.
Thanks

**Comment by mikenath223** [comment]
Are you saying i should delete my entire repo and create a new one?
**### Do you want me to file a complaint about you.**

**Comment by mikenath223** [comment]
You clearly want to frustrate us.
We were told to create a development branch and then create a new feature branch from the development branch then when we are done with the project  to create a pull request from the feature branch which is  what we have clearly done.

**Comment by KaushikShivam** [comment]
> Are you saying we should delete our entire repo and create a new one?
> **### Do you want us to file a complaint about you.**

Hello @mikenath223,
You're supposed to follow Github flow for this project. It is a **Strict mandatory Requirement** from Microverse and we're asked to not review the project if the correct flow is not used. 
I would highly recommend you to follow the steps and learn Github flow as they will teach you to become a better and professional developer. 

If you still need to escalate it and complain, you can write to the student success team.
If you have any other questions, you can message me on slack. :)

Best,
Shivam

**Comment by mikenath223** [comment]
What exactly are you saying you need to explain your exact point because you are not clear.
Are you saying our feature branch name isn't descriptive enough?
Because we have followed the rules outlined here below.
Microverse Onboarding - Google Chrome 29_10_2019 11_39_42 AM

**Comment by KaushikShivam** [comment]
> What exactly are you saying you need to explain your exact point because you are not clear.
> Are you saying our feature branch name isn't descriptive enough?
> Because we have followed the rules outlined here below.
> Microverse Onboarding - Google Chrome 29_10_2019 11_39_42 AM

Please follow these steps:
1. Create a new project and initialize the repo
2. Create a branch from the ```master``` and give it a descriptive name. Ex: design-teardown
3. Once you're done with the project, create a pull request from this branch to merge it into the ```master``` branch.
4. This is called github flow. You need to learn to follow this flow till the ruby - Advanceds building blocks section

I'd also suggest you read [this](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/) properly in order to avoid confusion in the future

If you have any more questions, feel free to ask.

Best of luck. 

Best,
Shivam

**Comment by mikenath223** [comment]
Cancel our code review request on the microverse dashboard so we can follow the instruction.
We are waiting.

**Comment by shshamim63** [comment]
Hi @mikenath223  and @frederico-miranda , 
Actually @KaushikShivam is correct. By the requirement of this project you were suppose to follow github flow, 
githubflow
But you guys have used gitflow. That are actually different. I haven't noticed that on the first review. And that raised the confusion. As mentioned by @KaushikShivam you have to follow the format.
And actually sorry for raising this confusion.
Best,
Shakhawat Hossain

**Comment by mikenath223** [comment]
It still says waiting for code review on the dashboard.
Please do cancel it.

**Comment by KaushikShivam** [comment]
> It still says waiting for code review on the dashboard.
> Please do cancel it.

It is cancelled and It will reflect soon.

**Pull request closed without merging**
